# Generated by Django 4.0.3 on 2022-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.TextField(max_length=500)),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ('name',), 'verbose_name': 'Cloth', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterIndexTogether(
            name='clothes',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='slug',
        ),
    ]
