# Generated by Django 4.0.3 on 2022-04-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ('-name',), 'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежды'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('name',), 'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('name',), 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
