# Generated by Django 4.0.3 on 2022-03-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sales_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='main.category'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='gender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='main.gender'),
        ),
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.category'),
        ),
        migrations.AddField(
            model_name='sales',
            name='gender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.gender'),
        ),
    ]
