# Generated by Django 4.0.3 on 2022-03-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clothes_category_clothes_gender_sales_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('include_description', models.TextField(max_length=500)),
                ('gender', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='main.gender')),
            ],
            options={
                'verbose_name': 'Gift_box',
                'verbose_name_plural': 'Gift_boxes',
            },
        ),
    ]
