# Generated by Django 4.0.3 on 2022-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='new_price',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='old_price',
            field=models.TextField(max_length=500),
        ),
    ]
