# Generated by Django 4.0.3 on 2022-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clothes_price_alter_gift_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='new_price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='old_price',
            field=models.CharField(max_length=500),
        ),
    ]
